# Generated by Django 5.0 on 2023-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("account", "Перевод на счет")],
                max_length=30,
                verbose_name="тип",
            ),
        ),
    ]
