# Generated by Django 5.0 on 2023-12-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="type",
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("account", "Перевод на счет")],
                default="cash",
                max_length=30,
                verbose_name="метод",
            ),
            preserve_default=False,
        ),
    ]
