# Generated by Django 5.0 on 2023-12-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_is_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="session id"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "платежная сессия",
                "verbose_name_plural": "платежные сессии",
                "ordering": ("-created_at", "payment"),
                "unique_together": {("payment", "session_id")},
            },
        ),
    ]
