# Generated by Django 5.0 on 2023-12-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_paymentsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsession",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="payments.payment",
            ),
        ),
    ]
