# Generated by Django 5.0 on 2023-12-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_paymentsession_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsession",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="payments.payment",
            ),
        ),
    ]
