# Generated by Django 5.0 on 2023-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(to="lessons.lesson"),
        ),
    ]
