# Generated by Django 5.0 on 2023-12-18 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_alter_course_options_alter_lesson_options_subscribe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribe",
            new_name="Subscription",
        ),
    ]
